In [532]:
import numpy as np

### Basic Array Creation

In [533]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [534]:
a = [1,3,4,5,6]
a

[1, 3, 4, 5, 6]

In [535]:
l = [1,3.4,5,'hello']
l

[1, 3.4, 5, 'hello']

In [536]:
np.array(l)

array(['1', '3.4', '5', 'hello'], dtype='<U32')

In [537]:
m = [[1,2,3],[4,5,6],[7,8,9]]
m

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [538]:
np.array(m)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Array Generational function

In [539]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [540]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [541]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [542]:
arr = np.linspace(1,10,100)
arr

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

#### Random Generation function

In [543]:
np.random.rand(10)

array([0.00960958, 0.27919011, 0.77762494, 0.89871907, 0.39900863,
       0.94347612, 0.88543728, 0.07453498, 0.88603304, 0.29795194])

In [544]:
np.random.randn(10)

array([ 0.15681094,  0.70486198, -1.71485792,  0.3400987 ,  0.74893118,
        0.06890079,  0.74928241, -0.56682991, -0.49131097, -1.43177533])

In [545]:
np.random.randint(10,20,6)

array([13, 18, 15, 12, 15, 17])

#### Array Attributes

In [546]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [547]:
arr.shape

(3, 3)

In [548]:
arr.size

9

In [549]:
arr.dtype

dtype('int64')

#### Array Methords

In [550]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [551]:
arr.min()

np.int64(1)

In [552]:
arr.max()

np.int64(9)

In [553]:
arr.sum()

np.int64(45)

In [554]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [555]:
arr.mean()

np.float64(5.0)

In [556]:
arr.std()

np.float64(2.581988897471611)

In [557]:
arr.argmax()

np.int64(8)

In [558]:
arr.argmin()

np.int64(0)

#### Reshaping and Resizing

In [559]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [560]:
arr = arr.reshape(15,2)


In [561]:
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24],
       [25, 26],
       [27, 28],
       [29, 30]])

# Section 2

#### Numpy Indexing And Slicing of Vector

In [562]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [563]:
arr[7]

np.int64(18)

In [564]:
arr[1:5]

array([12, 13, 14, 15])

In [565]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [566]:
arr_slice = arr[1::2]
arr_slice

array([12, 14, 16, 18, 20])

####     Numpy Indexing And Slicing of Matrix

In [567]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [568]:
arr[4]

array([21, 22, 23, 24, 25])

In [569]:
arr[0,4]

np.int64(5)

In [570]:
arr[0:2,1:3] 

array([[2, 3],
       [7, 8]])

In [571]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [572]:
arr[:,3]

array([ 4,  9, 14, 19, 24, 29])

#### Boolean Indexing

In [573]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [574]:
bool_index = arr % 2 == 0
bool_index 

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [575]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# Section 3

## Array Operations

#### *Arithmetic Operation*

In [576]:
a1 = np.arange(1,6)
a2 = np.arange(6,11)
a1
# a2 = np.array([ 6,  7,  8,  9, 10])

array([1, 2, 3, 4, 5])

In [577]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [578]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [579]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [580]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [581]:
a1 // a2

array([0, 0, 0, 0, 0])

In [582]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

#### *Broadcasting*

In [583]:
l = [1,2,3,4,5,6]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6])

In [584]:
arr + 10

array([11, 12, 13, 14, 15, 16])

In [585]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [586]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

##### *Deep And Shallow Copy*

In [587]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [588]:
slice = a[:5]
slice * 10

array([10, 20, 30, 40, 50])

In [589]:
# Deep Copy of a
b = a

In [590]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [591]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [592]:
# Shallow Copy 
b = a.copy()

##### *Matrix Operations*

In [593]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [594]:
A

array([[1, 2],
       [3, 4]])

In [595]:
B

array([[5, 6],
       [7, 8]])

In [596]:
# Matrix Dot Product
A @ B 
# or np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [597]:
# Transpose of Matrix
A.T

array([[1, 3],
       [2, 4]])

##### ADVANCE ARRAY MANIPULATION

##### *Stacking Array*

In [598]:
A

array([[1, 2],
       [3, 4]])

In [599]:
B

array([[5, 6],
       [7, 8]])

In [600]:
a = np.arange(1,5)
b = np.arange(5,9)

In [601]:
a


array([1, 2, 3, 4])

In [602]:
b

array([5, 6, 7, 8])

In [603]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [604]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [605]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

##### *splitting array*

In [606]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [607]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [608]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

# Exersises 

##### Valid Sudoku

In [609]:

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [610]:
b = np.sum(s, axis = 1)
for i in b :
    if i != 45:
        print("Sudoku is not valid")
        break
print("for rows it is valid")

for rows it is valid


In [611]:
c = np.sum(s,axis = 0)
for i in c:
    if i != 45 :
        print("sudoku is not valid")
        break
print("for column it is valid")

for column it is valid


In [612]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


##### General Questions


In [613]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [614]:
#Get the shape of the matrix
data.shape

(5, 3)

In [615]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [616]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [617]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [618]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]
    


array([[19, 92, 88]])

In [619]:
#Increase Math marks of all students by 5.
data[:,1] +=5 
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [625]:
#Find how many students are younger than 19.
len(data[data[:,0] < 19])


3

In [627]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis = 0)

array([86.6, 83.2])

In [628]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80) ]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [629]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])